### PR TITLE
Fix handling of problematic iframe loads.

### LINKED ISSUE #82: Sub-tests which fail to invoke “x-test” (400, 500, SPA Fallbacks, etc.) silently pass or hang.
## Context

Registering an iframe-based sub-test against a URL that doesn’t serve a real `x-test` page produces one of two wrong outcomes depending on the failure mode — both confusing, neither surfacing the actual problem:

- Silent pass. A `404`, a `500`, or an “SPA fallback” (where the server returns `index.html` for unknown routes with a `200`) loads “successfully” from the browser’s perspective. The iframe fires load, the child document has no `x-test` in it, nothing ever publishes `x-test-suite-ready`, and the suite reports a clean `1..0 ok` as if the test had zero assertions.
- Indefinite hang. An unreachable host (DNS failure, connection refused, offline) never fires either `load` or `error` on the iframe in any useful timeframe, and the run just sits there.

Both cases _look_ like success or a stall when the real answer is “your test file doesn’t exist” or “your dev server isn’t running.”

## Proposal

The root frame should race the three outcomes per iframe load:

1. A 30-second timeout (`Timed out loading <url>`) — catches unreachable hosts and indefinite hangs.
2. An `iframe.error` event (`Failed to load <url>`) — catches the network-level failures that do fire.
3. An `iframe.load` event, gated by a follow-up handshake for suite initialization.

## Example

```js
test('./does-not-exist.html');           // 404 → 1..0 ok
test('./some/spa/route');                // 200, wrong content → 1..0 ok
test('http://127.0.0.1:9999/test.html'); // unreachable → hang
```

### PR DESCRIPTION
**Pull request by theengineear**
Fixes the handling and logging for the failures modes when loading an iframe element for a sub-test:

```js
test('./does-not-exist.html');           // 404 → 1..0 ok
test('./some/spa/route');                // 200, wrong content → 1..0 ok
test('http://127.0.0.1:9999/test.html'); // unreachable → hang
```

Closes #82.

### CODE REVIEW

File: x-test-root.js [hunk 1]
```diff
@@ -74,6 +81,48 @@ export class XTestRoot {
...
+
+  /**
+   * @param {any} context
+   * @param {any} data
+   */
+  static checkInitialized(context, data) {
+    if (!context.state.ended) {
+      const test = context.state.tests[data.testId];
+      if (!test.initialized) {
+        XTestRoot.bail(context, new Error(`Failed to initialize ${data.href}`));
```
Comment (theengineear) [inline x-test-root.js:121]: This is an example of the more fine-grained logging we can do here. In this case, the frame _did_ load just fine (from the browser’s perspective), but no tests actually booted, and we can now message accurately about that.
