### PR TITLE
Fix “TAP Version 14” > “TAP version 14” text.

### LINKED ISSUE #88: Use lowercase “v” in “TAP version 14” version line.
This is super minor, just noticed that we should be outputting `TAP version 14`, not `TAP Version 14` (capital `V`).

As per the TAP 14 [specification](https://testanything.org/tap-version-14-specification.html):

>**Version**
>To indicate that this is TAP14 the first line must be
>`TAP version 14`

### PR DESCRIPTION
**Pull request by theengineear**
Simple change to make the “V” lowercase. See TAP 14 specification:

https://testanything.org/tap-version-14-specification.html

Closes #88.

### CODE REVIEW

File: x-test-tap.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ export class XTestTap {
    * @returns {string}
    */
   static version() {
-    return 'TAP Version 14';
+    return 'TAP version 14';
```
Comment (theengineear) [inline x-test-tap.js:15]: Super silly, but might as well be exacting. Most consumers are alright with a case-insensitive match — but, the spec says what it says.
